server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://101.132.79.111:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: wjq200165
  main:
    # 解决因循环引用导致报错
    allow-circular-references: true

  cloud:
    nacos:
      server-addr: 101.132.79.111:8848 # nacos服务地址
      discovery:
        ip: 42.192.152.233:8080 # 指定当前服务再nacos中的ip地址

  # 设置端口微服务名,注册/调用服务,都是根据这个来的
  application:
    name: reggie # 服务名称

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 自动分配id，id由雪花算法在数据存入数据库时自动生成
      id-type: ASSIGN_ID


