server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://101.132.79.111:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: wjq200165
  main:
    # 解决因循环引用导致报错
    allow-circular-references: true

#  cloud:
#    nacos:
#      server-addr: 101.132.79.111:8848 # nacos服务地址
#      discovery:
#        ip: 42.192.152.233:8080 # 指定当前服务再nacos中的ip地址
#    # 设置端口微服务名,注册/调用服务,都是根据这个来的
#  application:
#    name: reggie # 服务名称

  redis:
    host: 42.192.152.233
    port: 6379
    password: wjq200165
    timeout: 5000ms # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 5 # 连接池中的最大空闲连接
        min-idle: 3 # 连接池中的最小空闲连接
        max-wait: 5000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）

  cache:
    redis:
      time-to-live: 1800000 # 设置cache缓存有效期 30分钟


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 自动分配id，id由雪花算法在数据存入数据库时自动生成
      id-type: ASSIGN_ID


