server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: 你的mysql地址
      username: root
      password: 密码
  main:
    # 解决因循环引用导致报错
    allow-circular-references: true

  redis:
    host: redis地址
    port: 6379
    password: 密码
    timeout: 5000ms # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 5 # 连接池中的最大空闲连接
        min-idle: 3 # 连接池中的最小空闲连接
        max-wait: 5000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）

  cache:
    redis:
      time-to-live: 1800000 # 设置cache缓存有效期 30分钟


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 自动分配id，id由雪花算法在数据存入数据库时自动生成
      id-type: ASSIGN_ID


